apiVersion: v1
kind: PersistentVolume
metadata:
  name: nagp-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/nagp-postgres
  persistentVolumeReclaimPolicy: Retain
