apiVersion: v1
kind: ConfigMap
metadata:
  name: nagp-postgres-init-sql
data:
  init.sql: |
    CREATE TABLE items (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      quantity INTEGER DEFAULT 0
    );

    INSERT INTO items (name, quantity) VALUES
    ('Laptop', 25),
    ('Wireless Mouse', 100),
    ('Office Chair', 40),
    ('Notebook - A4', 200),
    ('LED Monitor - 24 inch', 30),
    ('USB-C Cable', 150),
    ('Mechanical Keyboard', 75);
