apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS items (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100)
    );
    INSERT INTO items (name) VALUES
      ('Item A'), ('Item B'), ('Item C'), ('Item D'), ('Item E');
